import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

// Helper to generate URL slugs safely
function toSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

const docsDir = path.resolve(__dirname, 'docs');

const sidebars: SidebarsConfig = {
  // We start with the base manual links for the main sidebar
  tutorialSidebar: [
    
  ],
};

let fields = [];
try {
  if (fs.existsSync(docsDir)) {
    fields = fs.readdirSync(docsDir, { withFileTypes: true })
      .filter(dirent => dirent.isDirectory() && !dirent.name.startsWith('.'))
      .map(dirent => dirent.name);
  }
} catch (err) {
  console.warn('[sidebars.ts] Could not read docs directory:', err.message);
}

  fields.forEach(field => {
    const fieldSlug = toSlug(field);
    const fieldDir = path.join(docsDir, field);
    let courses = [];
    try {
      courses = fs.readdirSync(fieldDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory() && !dirent.name.startsWith('.'))
        .map(dirent => dirent.name);
    } catch (err) {
      console.warn(`[sidebars.ts] Could not read field directory ${fieldDir}:`, err.message);
    }

    if (courses.length > 0) {
      // 1. Add this field and its courses to the main tutorial sidebar
      const fieldItems = courses.map(course => {
        const courseSlug = toSlug(course);
        return {
          type: 'link',
          label: course, // Use directory name as label
          // Cast the type strictly for Docusaurus SidebarsConfig
          href: `/docs/${fieldSlug}/${courseSlug}` 
        };
      });

      // We have to bypass TS checking slightly for dynamic additions, 
      // but Docusaurus sidebars config accepts category objects.
      (sidebars.tutorialSidebar as any[]).push({
        type: 'category',
        label: field,
        link: {
          type: 'generated-index',
          slug: `/${fieldSlug}`
        },
        items: fieldItems
      });

      // 2. Generate an isolated sidebar for each course
      courses.forEach(course => {
        const courseSlug = toSlug(course);
        // Create a unique key for this course's sidebar
        const sidebarKey = `${fieldSlug}-${courseSlug}-sidebar`;
        
        sidebars[sidebarKey] = [
          {
            type: 'link',
            label: '← Back to Main Docs',
            href: '/'
          },
          {
            type: 'category',
            label: course,
            link: {
              type: 'generated-index',
              slug: `/${fieldSlug}/${courseSlug}`
            },
            items: [
              {
                type: 'autogenerated',
                dirName: `${field}/${course}`,
              }
            ]
          }
        ];
      });
    }
  });
export default sidebars;
